In [ ]:
print('hello world')

hello world


In [ ]:
#hi please listen single line comment
"""i am teaching here
             python and datascience
              with AI and greenskills
              """

'i am teaching here \n             python and datascience\n              with AI and greenskills\n              '

In [ ]:
import keyword
print(keyword.kwlist)

['False', 'None', 'True', 'and', 'as', 'assert', 'async', 'await', 'break', 'class', 'continue', 'def', 'del', 'elif', 'else', 'except', 'finally', 'for', 'from', 'global', 'if', 'import', 'in', 'is', 'lambda', 'nonlocal', 'not', 'or', 'pass', 'raise', 'return', 'try', 'while', 'with', 'yield']


In [ ]:
# @title
val1=10
print(val1)
print(type(val1))
print(val1,"is integer?",isinstance(val1,int))

10
<class 'int'>
10 is integer? True


In [ ]:
var_2 = 'HI'
var_3 = 45.4
var_4 = 5+6j
var_5 = True
print(var_2, type(var_2))
print(var_3, type(var_3))
print(var_4, type(var_4))
print(var_5, type(var_5))

HI <class 'str'>
45.4 <class 'float'>
(5+6j) <class 'complex'>
True <class 'bool'>


In [ ]:
print(var_2, 'is string', isinstance(var_2, str))

HI is string True


In [ ]:
x, y ,z,a,b,c = 12, 13, 14, 'Marks', True, 5.87
print(x,y,z,a,b,c)

12 13 14 Marks True 5.87


In [ ]:
num = (12,53,56.6)
g,h,i = num
print(g,h,i)


12 53 56.6


In [ ]:
e_st =''
e_st2 = str()
print(e_st, type(e_st), e_st2, type(e_st2))

 <class 'str'>  <class 'str'>


In [ ]:
st = "***Welcome  to the python world***"
print(st)
print(len(st))
print(st.strip('*'))
print(st.upper())
print(st.lower())

***Welcome  to the python world***
34
Welcome  to the python world
***WELCOME  TO THE PYTHON WORLD***
***welcome  to the python world***


In [ ]:
st[19:25]='real'

TypeError: 'str' object does not support item assignment

In [ ]:
st

In [ ]:
e_list = []
e_list2 = list()
print(e_list, type(e_list),  e_list2,type(e_list2))

[] <class 'list'> [] <class 'list'>


In [ ]:
num_list = [34,667,889.6, 67]
print(num_list)
mix_list = ['hai', True, 56, 67.6]
print(mix_list)

[34, 667, 889.6, 67]
['hai', True, 56, 67.6]


In [ ]:
mix_list[2] = 45
print(mix_list)


['hai', True, 45, 67.6]


In [ ]:
mix_list[2:4]

[45, 67.6]

In [ ]:
mix_list[-4:-2]

['hai', True]

In [ ]:
mix_list[::-1][2:4]

[True, 'hai']

In [ ]:
example=["sunday","monday","tuesday","wednesday",'Thursday', 'Friday','Saturday']
print(example[3:6])


['wednesday', 'Thursday', 'Friday']


In [ ]:
example[-6:-1]

['monday', 'tuesday', 'wednesday', 'Thursday', 'Friday']

In [ ]:
example[0][0:3]

'sun'

In [ ]:
ls= ['first', 1, 'second',2 , True, 67.7, 56.7]
first', 1, 'second
2 , True, 67.7
56.7
'second',2


In [ ]:
ls[0:3]
ls[3:6]
ls[2:4]

['second', 2]

In [ ]:
example[1][0:3]

'mon'

In [ ]:
 example=["sunday,monday,tuesday,wednesday"]
example1=["weekdays","weekends"]
week=example+example1
print(week)

['sunday,monday,tuesday,wednesday', 'weekdays', 'weekends']


In [ ]:
week.append('holiday')

In [ ]:
week.insert(4,'thursday')

In [ ]:
week.pop()

'thursday'

In [ ]:
week.insert(1,'Thursday')

In [ ]:
week.remove('weekends')
week

['sunday,monday,tuesday,wednesday', 'Thursday', 'weekdays', 'holiday']

In [ ]:
example=["weekdays","weekends"]
example=example*3
print(example)


['weekdays', 'weekends', 'weekdays', 'weekends', 'weekdays', 'weekends']


In [ ]:
example=("first","second","third","fourth")
print(example)
print(example[1:3])

('first', 'second', 'third', 'fourth')
('second', 'third')


In [ ]:
tuple(['first','second','third'])
list(('first','second','third'))
list("scalar")

['s', 'c', 'a', 'l', 'a', 'r']

In [ ]:
e_tup = ()
print(type(e_tup))
e_tup2 = tuple()
print(type(e_tup2))

<class 'tuple'>
<class 'tuple'>


In [ ]:
tup = ('hi', 56.6, 87, True)
tup

('hi', 56.6, 87, True)

In [ ]:
s1 = {5}
s={}
s2 = set()
print(type(s1))
print(type(s2))
print(type(s))

<class 'set'>
<class 'set'>
<class 'dict'>


In [ ]:
eset ={1:2}
print(type(eset))
e_set2 = set()
print(type(e_set2))

<class 'dict'>
<class 'set'>


In [ ]:
mydict={1:'one','A':'two',3:'three', 2: 'two'}
mydict

{1: 'one', 'A': 'two', 3: 'three', 2: 'two'}

In [ ]:
mydict.keys()

dict_keys([1, 'A', 3, 2])

In [ ]:
mydict.values()

dict_values(['one', 'two', 'three', 'two'])

In [ ]:
mydict.items()

dict_items([(1, 'one'), ('A', 'two'), (3, 'two')])

In [ ]:
keys={'a','b','c','d'}
values={10}
mydict3=dict.fromkeys(keys,values)
mydict3

{'c': {10}, 'a': {10}, 'd': {10}, 'b': {10}}

In [ ]:
keys={'a','b','c','d'}
values=[10,20,30]
mydict3=dict.fromkeys(keys,values)
mydict

{1: 'one', 'A': 'two', 3: 'three'}

In [ ]:
set_1 = {23,56,56,34,23,23}
set_1

{23, 34, 56}

In [ ]:
x<>5

In [ ]:
a = a+10
a+=10

In [ ]:
a= 1000
b = 1000
print( a is b)
b= a
print(a is b)

False
True


In [ ]:
x = int(input("enter your marks:"))
if x >35:
  print("you passed the exam")

enter your marks:34


In [ ]:
name = input("enter the name:")
reverse_name = name[::-1]
if name ==reverse_name:
    print(f"{name} is palindrome")
else:
    print(f"{name} is not palindrome")

enter the name:malayalam
malayalam is palindrome


In [ ]:
a = int(input("enter a number"))
if a % 2== 0:
  print(a, "is even number")
else:
  print(a,"is odd number")

enter a number9
9 is odd number


In [ ]:
marks = int(input("enter the marks"))
if marks > 90:
  print("grade A")
elif marks > 80:
  print("grade B")
elif marks > 70:
  print("grade C")
elif marks > 60:
  print("grade D")
else:
  print("grade E")

enter the marks78
grade C


In [ ]:
pass_year = int(input("enter the year"))
dept = input("enter the dept")
if pass_year == 2025:
  if dept =="cse":
    print("campus eligible")
  else:
    print("not eligible")
else:
  print("Final years only")


enter the year2024
enter the deptcse
Final years only


In [ ]:
for i in range(6, 39,3):
  print(i)

6
9
12
15
18
21
24
27
30
33
36


In [ ]:
for i in range(10,20):
  print(i)

10
11
12
13
14
15
16
17
18
19


In [ ]:
s={1,2,3}
print(s)
s=set([1,2,3])
print(s)
s={1,2,3,3,2,4,5,5}
print(s)

{1, 2, 3}
{1, 2, 3}
{1, 2, 3, 4, 5}


In [ ]:
s={1,2,3,3,2,4,5,5}
print(s)
s.add(6)
print(s)


{1, 2, 3, 4, 5}
{1, 2, 3, 4, 5, 6}


In [ ]:
s={1,2,3,3,4,5,5}
print(s)
s.update([6,7,8])

{1, 2, 3, 4, 5}


In [ ]:
s={1,2,3,3,4,5,5}
print(s)
s.remove(4)
print(s)
s.discard(1)

{1, 2, 3, 4, 5}
{1, 2, 3, 5}


In [ ]:
x=int(input("enter a 1st number"))
y=int(input("enter a 2nd number"))
sum=x+y
diff=x-y
muilt=x*y
div=x/y
float=x//y
modulus=x%y

enter a 1st number10
enter a 2nd number20


In [ ]:
print(f"sum of two number:{sum}")
print(f"diff of two number:{diff}")
print(f"muilt of two number:{muilt}")
print(f"div of two number:{div}")
print(f"float of the number:{float}")
print(f"modulus of two number:{modulus}")

sum of two number:30
diff of two number:-10
muilt of two number:200
div of two number:0.5
float of the number:0
modulus of two number:10


In [ ]:
for i in range(0,100):
  print(f'{i} x 2 =',i*2 )

0 x 2 = 0
1 x 2 = 2
2 x 2 = 4
3 x 2 = 6
4 x 2 = 8
5 x 2 = 10
6 x 2 = 12
7 x 2 = 14
8 x 2 = 16
9 x 2 = 18
10 x 2 = 20
11 x 2 = 22
12 x 2 = 24
13 x 2 = 26
14 x 2 = 28
15 x 2 = 30
16 x 2 = 32
17 x 2 = 34
18 x 2 = 36
19 x 2 = 38
20 x 2 = 40
21 x 2 = 42
22 x 2 = 44
23 x 2 = 46
24 x 2 = 48
25 x 2 = 50
26 x 2 = 52
27 x 2 = 54
28 x 2 = 56
29 x 2 = 58
30 x 2 = 60
31 x 2 = 62
32 x 2 = 64
33 x 2 = 66
34 x 2 = 68
35 x 2 = 70
36 x 2 = 72
37 x 2 = 74
38 x 2 = 76
39 x 2 = 78
40 x 2 = 80
41 x 2 = 82
42 x 2 = 84
43 x 2 = 86
44 x 2 = 88
45 x 2 = 90
46 x 2 = 92
47 x 2 = 94
48 x 2 = 96
49 x 2 = 98
50 x 2 = 100
51 x 2 = 102
52 x 2 = 104
53 x 2 = 106
54 x 2 = 108
55 x 2 = 110
56 x 2 = 112
57 x 2 = 114
58 x 2 = 116
59 x 2 = 118
60 x 2 = 120
61 x 2 = 122
62 x 2 = 124
63 x 2 = 126
64 x 2 = 128
65 x 2 = 130
66 x 2 = 132
67 x 2 = 134
68 x 2 = 136
69 x 2 = 138
70 x 2 = 140
71 x 2 = 142
72 x 2 = 144
73 x 2 = 146
74 x 2 = 148
75 x 2 = 150
76 x 2 = 152
77 x 2 = 154
78 x 2 = 156
79 x 2 = 158
80 x 2 = 160
81 x 2 = 162

In [ ]:
count =0
i = int(input("enter the number of iteration"))
while count <i:
  print(count)
  count = count+1



In [ ]:
user = ""
while user!= 'quit':
      user = input("enter the quit to stop or else type anything to continue: ")
      print(user)

enter the quit to stop or else type anything to continue: fggjdf
fggjdf
enter the quit to stop or else type anything to continue: oo'ih
oo'ih
enter the quit to stop or else type anything to continue: quit
quit


In [ ]:
def greetings(name):
  print(f'Hi {name} ,welcome to python world')

In [ ]:
greetings('gautam')

Hi gautam ,welcome to python world


In [ ]:
def add(a,b):
  return a+b

In [ ]:
add(67,98)

165

In [ ]:
def calc(num1, num2, ops):
  if ops =='+':
    print(f'sum of num1 and num2 is {num1+num2}')
  elif ops =='-':
    print(f'diff of num1 and num2 is {num1-num2}')
  elif ops =='*':
    print(f'muilt of num1 and num2 is {num1*num2}')
  elif ops =='/':
    print(f'div of num1 and num2 is {num1/num2}')

In [ ]:
calc(56,76,'*')

muilt of num1 and num2 is 4256


In [ ]:
hypo = lambda x,y:(x**2 +y**2)


In [ ]:
hypo(25,20)

1025

In [ ]:
even_num  = [i**2 for i in range(0,21,2) if i >10]
print(even_num)

[144, 196, 256, 324, 400]


In [ ]:
for i in range(100):
  if i >20:
    break
  print(i)




In [ ]:
for i in range(100):
  if i >20:
    pass
  print(i)

In [ ]:
for i in range(100):
  if i%2==1:
    continue
  print(i)

In [ ]:
import numpy as np
arr1 = np.array([1,2,3])
print(arr1)

[1 2 3]


In [ ]:
arr_2d = np.array([[1,2,3], [4,5,6],[7,8,9]])
print(arr_2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
arr_3d = np.array([[[1,24,5],[34,354,54],[45,34,23]]])
print(arr_3d)

[[[  1  24   5]
  [ 34 354  54]
  [ 45  34  23]]]


In [ ]:
print(type(arr1),type(arr_2d), type(arr_3d))

<class 'numpy.ndarray'> <class 'numpy.ndarray'> <class 'numpy.ndarray'>
<class 'numpy.ndarray'> <class 'numpy.ndarray'> <class 'numpy.ndarray'>


In [ ]:
print(arr1.ndim, arr_2d.ndim, arr_3d.ndim)


1 2 3


In [ ]:
print(arr1.shape, arr_2d.shape, arr_3d.shape)

(3,) (3, 3) (1, 3, 3)


In [ ]:
arr1.dtype

dtype('int64')

In [ ]:
str_n = np.array([65.7,87.8,67.8])
str_n.dtype

dtype('float64')

In [ ]:
data= np.random.randint(50, size=(5,10))
data

array([[47, 45, 32, 36, 21,  0,  7, 16, 44, 27],
       [12, 10, 46, 45, 16, 31,  1,  5, 33,  8],
       [45, 45, 44,  8,  0, 25, 43,  4, 43, 38],
       [35,  7, 40,  9, 17, 14,  0, 30,  9, 32],
       [29, 36, 32, 14, 28, 35, 26,  6, 37, 37]])

In [ ]:
np.unique(data)

In [ ]:
np.max(data)

np.int64(49)

In [ ]:
sq = np.power(data, 2)
sq

In [ ]:
np.sqrt(sq)

In [ ]:
one = np.ones((3,3))
one

In [ ]:
zero = np.zeros((3,3))
zero

In [ ]:
np.dot(one,zero)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('/content/green_supply_chain_dataset_1000.csv')

In [ ]:
df.head(10)

ID    Product_Type  Raw_Material_Usage_kg  Energy_Consumption_kWh  \
0   1  Pharmaceutical             187.102474              372.345525   
1   2            Food             117.375305               82.437951   
2   3      Automotive             142.363657               82.065527   
3   4            Food             185.274882               55.448814   
4   5            Food             144.375341              480.425629   
5   6         Apparel              38.982418              381.878762   
6   7      Automotive             119.494788              208.963134   
7   8      Automotive             125.275859              183.441012   
8   9      Automotive              90.584828              207.366453   
9  10            Food             149.924405              398.594089   

   Waste_Generated_kg  Transport_Distance_km  CO2_Emissions_kg  \
0            4.580997            2708.230192        206.072501   
1           31.494820             605.998543        794.003359   
2           49.077714             945.366997        166.372969   
3           10.315275            2883.074057        653.161326   
4           39.837161            1552.152306        167.653725   
5           45.487041            4697.747070        117.008856   
6           47.241378            4111.827124        913.958029   
7           48.046645            4919.479312        230.622328   
8           26.551522            1372.387111        830.187647   
9           48.888087            4851.645801        567.399328   

   Manufacturing_Energy_kWh  Renewable_Energy_%       Cost_$  \
0                195.022097           77.312801  4696.896464   
1                784.206729           31.899124   989.721787   
2                775.047264           16.863118  1321.186084   
3                214.610271           46.877202  1464.672539   
4                309.596187           13.996935   381.536655   
5                170.108498           17.738022   790.650193   
6                290.202319           25.357257  4934.479630   
7                671.169053           42.504517  1713.040339   
8                364.820925           40.327565   753.445234   
9                161.877877           65.978430   713.558054   

   Delivery_Time_days  Sustainability_Score  
0                   2                 81.25  
1                   4                 37.55  
2                   2                 41.17  
3                   1                 56.79  
4                  10                 45.27  
5                  13                 45.58  
6                  13                 16.49  
7                   3                 51.69  
8                  12                 43.13  
9                   8                 54.98

In [ ]:
df.tail()

In [ ]:
df.info()

In [ ]:
df.isnull().sum()

In [ ]:
df.shape

(1000, 12)

In [ ]:
df.describe()

ID  Raw_Material_Usage_kg  Energy_Consumption_kWh  \
count  1000.000000            1000.000000             1000.000000   
mean    500.500000             105.046415              274.277250   
std     288.819436              55.616518              129.959635   
min       1.000000              10.880084               50.060612   
25%     250.750000              54.782690              166.916381   
50%     500.500000             105.827254              274.697786   
75%     750.250000             151.558389              388.052288   
max    1000.000000             199.888608              499.256380   

       Waste_Generated_kg  Transport_Distance_km  CO2_Emissions_kg  \
count         1000.000000            1000.000000       1000.000000   
mean            25.418835            2506.296581        523.203938   
std             14.103731            1401.083323        274.876548   
min              1.000570             100.150522         50.896245   
25%             13.127740            1315.783701        286.755243   
50%             25.601655            2471.166625        511.160758   
75%             37.669786            3678.120070        760.403022   
max             49.978327            4988.972006        999.382785   

       Manufacturing_Energy_kWh  Renewable_Energy_%       Cost_$  \
count               1000.000000         1000.000000  1000.000000   
mean                 447.026783           44.153032  2502.760536   
std                  202.134494           20.010416  1364.706793   
min                  100.999840           10.016870   201.166085   
25%                  272.351083           26.836517  1311.317224   
50%                  444.503275           44.008122  2388.768189   
75%                  628.693850           60.430379  3642.199461   
max                  799.622477           79.923329  4980.861360   

       Delivery_Time_days  Sustainability_Score  
count         1000.000000           1000.000000  
mean             7.668000             51.207240  
std              4.027903             14.768154  
min              1.000000             12.800000  
25%              4.000000             40.155000  
50%              8.000000             50.795000  
75%             11.000000             61.830000  
max             14.000000             91.530000

In [ ]:
df.describe(include = 'object')


Product_Type
count          1000
unique            5
top     Electronics
freq            210

In [ ]:
df[['Product_Type','Delivery_Time_days']]

Product_Type  Delivery_Time_days
0    Pharmaceutical                   2
1              Food                   4
2        Automotive                   2
3              Food                   1
4              Food                  10
..              ...                 ...
995         Apparel                   8
996     Electronics                  13
997     Electronics                  12
998  Pharmaceutical                   8
999      Automotive                  10

[1000 rows x 2 columns]

In [ ]:
df.iloc[:100,10:]

Cost_$  Delivery_Time_days  Sustainability_Score
500  3164.934014                   5                 36.28
501  3293.231214                   9                 54.85
502   336.019762                  13                 55.60
503  4176.945246                   6                 60.60
504  3983.720999                   5                 28.82
..           ...                 ...                   ...
995   477.383346                   8                 49.61
996   875.136028                  13                 37.19
997  3639.833296                  12                 38.07
998  2298.951912                   8                 68.98
999  2137.033380                  10                 23.28

[500 rows x 3 columns]